services:
  lesson-server:
    build:
      context: ../hoz-mcp
      dockerfile: Dockerfile-lesson
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    restart: unless-stopped 
  room-server:
    build:
      context: ../hoz-mcp
      dockerfile: Dockerfile-room
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
    restart: unless-stopped 